"""Public yukicoder API client surface."""

from yukitools_rime.api.client import (
    DEFAULT_BASE_URL,
    USER_AGENT,
    APIError,
    HTTPError,
    YukicoderAPIError,
    YukicoderClient,
    YukicoderHTTPError,
    YukicoderTransportError,
)
from yukitools_rime.api.types import (
    JUDGE_STATUS_COMPILE_ERROR,
    JUDGE_STATUS_OK,
    EditorialContent,
    EditorialRequest,
    GeneratorContent,
    GeneratorRequest,
    JudgeCodeContent,
    JudgeCodeRequest,
    JudgeCodeSaveResponse,
    Language,
    ProblemEditContent,
    ProblemEditRequest,
    ResponseFormatError,
    SaveResponse,
    SolutionRequest,
    UploadResponse,
    Which,
    judge_status_is_final,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "JUDGE_STATUS_COMPILE_ERROR",
    "JUDGE_STATUS_OK",
    "USER_AGENT",
    "APIError",
    "EditorialContent",
    "EditorialRequest",
    "GeneratorContent",
    "GeneratorRequest",
    "HTTPError",
    "JudgeCodeContent",
    "JudgeCodeRequest",
    "JudgeCodeSaveResponse",
    "Language",
    "ProblemEditContent",
    "ProblemEditRequest",
    "ResponseFormatError",
    "SaveResponse",
    "SolutionRequest",
    "UploadResponse",
    "Which",
    "YukicoderAPIError",
    "YukicoderClient",
    "YukicoderHTTPError",
    "YukicoderTransportError",
    "judge_status_is_final",
]
